export enum Sizes {
  XS = 'XS',
  S = 'S',
  M = 'M',
  L = 'L',
  XL = 'XL',
}

export enum MainCategories {
  MAN = 'MAN',
  WOMAN = 'WOMAN',
  CHILD = 'CHILD',
  PET = 'PET',
  ELECTRONIC = 'ELECTRONIC',
  SPORT = 'SPORT',
}

export enum Categories {
  CLOTHES = 'CLOTHES',
  SHOES = 'SHOES',
  ACCESSORY = 'ACCESSORY',
  ELECTRONIC = 'ELECTRONIC',
  CAT = 'CAT',
  DOG = 'DOG',
  BIRD = 'BIRD',
  KITCHEN = 'KITCHEN',
  OTHER = 'OTHER',
  SPORTSWEAR = 'SPORTSWEAR',
  WHITE_APPLIANCES = 'WHITE_APPLIANCES',
  GYM_SHOE = 'GYM_SHOE',
  SPORTS_EQUIPMENT = 'SPORTS_EQUIPMENT',
  SPORTS_NUTRITION = 'SPORTS_NUTRITION',
}

export enum SubCategories {
  JUMPER = 'JUMPER',
  T_SHIRT = 'T_SHIRT',
  SHIRTS = 'SHIRTS',
  PANTS = 'PANTS',
  COATS = 'COATS',
  JACKET = 'JACKET',
  SUIT = 'SUIT',
  UNIFORM = 'UNIFORM',

  SPORTS_SHOES = 'SPORTS_SHOES',
  CASUAL_SHOE = 'CASUAL_SHOE',
  SPIKES = 'SPIKES',
  CLASSICAL = 'CLASSICAL',
  OUTDOOR = 'OUTDOOR',

  GOGGLES = 'GOGGLES',
  WATCH = 'WATCH',
  WALLET = 'WALLET',
  BAG = 'BAG',
  HATS = 'HATS',

  SHAVER = 'SHAVER',

  DRY_FOOD = 'DRY_FOOD',
  WET_FOOD = 'WET_FOOD',
  VITAMIN = 'VITAMIN',
  BALL = 'BALL',
  SCRATCHING_POST = 'SCRATCHING_POST',
  CAT_LITTER = 'CAT_LITTER',

  DOG_COLLAR = 'DOG_COLLAR',
  DOG_TOILET = 'DOG_TOILET',

  FOOD = 'FOOD',
  CARE = 'CARE',
  CAGE = 'CAGE',
  LUNCH_BOX = 'LUNCH_BOX',
  WATER_BOX = 'WATER_BOX',

  ICEBOX = 'ICEBOX',
  WASHING_MACHINE = 'WASHING_MACHINE',
  DISHWASHER = 'DISHWASHER',
  STOVE = 'STOVE',

  KETTLE = 'KETTLE',
  COFFEE_MAKER = 'COFFEE_MAKER',
  SANDWICH_MAKER = 'SANDWICH_MAKER',
  MIKSER = 'MIKSER',
  WEIGHT = 'WEIGHT',

  TV = 'TV',
  VACUUM_CLEANER = 'VACUUM_CLEANER',
  ELECTRIC_TOOTHBRUSH = 'ELECTRIC_TOOTHBRUSH',
  EARPHONE = 'EARPHONE',
  SPEAKER = 'SPEAKER',

  SPORTS_T_SHIRT = 'SPORTS_T_SHIRT',
  SPORTS_SHORTS = 'SPORTS_SHORTS',
  TRACKSUIT = 'TRACKSUIT',
  SPORTS_SWEATSHIRT = 'SPORTS_SWEATSHIRT',

  RUNNING_SHOES = 'RUNNING_SHOES',
  ASTROTURF_SHOES = 'ASTROTURF_SHOES',
  BASKETBALL_SHOES = 'BASKETBALL_SHOES',
  WALKING_SHOE = 'WALKING_SHOE',
  OUTDOOR_SHOES = 'OUTDOOR_SHOES',
  OUTDOOR_BOT = 'OUTDOOR_BOT',

  SKATEBOARD = 'SKATEBOARD',
  CAMPING_TOOLS = 'CAMPING_TOOLS',
  MOUNTAINEERING_CLIMBING = 'MOUNTAINEERING_CLIMBING',
  TENT = 'TENT',
  FISHING_SUPPLIES = 'FISHING_SUPPLIES',
  DUMBBELL = 'DUMBBELL',

  PROTEIN_POWDER = 'PROTEIN_POWDER',
  AMINO_ACIDS = 'AMINO_ACIDS',
  CARBOHYDRATE = 'CARBOHYDRATE',
  CREATINE = 'CREATINE',
}
